drop table IF EXISTS clients cascade;
drop table IF EXISTS phones cascade;
drop table IF EXISTS emails cascade;

create TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  surname VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  patronymic VARCHAR(50) NOT NULL,
  birth_day DATE NOT NULL,
  balance DOUBLE PRECISION NOT NULL,
  start_deposit DOUBLE PRECISION NOT NULL,
  login VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT pk_client PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS phones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  phone_number VARCHAR(10) NOT NULL UNIQUE,
  client_id BIGINT NOT NULL,
  CONSTRAINT fk_owner_phone FOREIGN KEY (client_id) REFERENCES clients(id) ON delete CASCADE,
  CONSTRAINT pk_phone PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  client_id BIGINT NOT NULL,
  CONSTRAINT fk_owner_email FOREIGN KEY (client_id) REFERENCES clients(id) ON delete CASCADE,
  CONSTRAINT pk_email PRIMARY KEY (id)
);